### ISSUE TITLE
Chapter 3 Section 3.3.1 Topology typo

### ISSUE THREAD

**Issue by yeshasvitirupachuri** [traversaro/traversaro-phd-thesis#12]
In section [3.3.1 Topology](https://github.com/traversaro/phd-thesis/blob/afae11ded681cc247b6e306296f80750d003262a/thesis/Chapter30MultiBody/chapter-multibody.tex#L260), there is a typo

![Screenshot from 2019-11-04 09-15-16](https://user-images.githubusercontent.com/6505998/68107317-bc7fc700-fee4-11e9-8771-9d5b111b1744.png)

`threat` ------------> `treat`

**Comment by traversaro** [comment]
Can you check if this was fixed by https://github.com/traversaro/phd-thesis/pull/13 ?

**Comment by traversaro** [comment]
The fix is not live at https://traversaro.github.io/phd-thesis/traversaro-phd-thesis.pdf .
