### ISSUE TITLE
Update readme with thesis citation 

### ISSUE THREAD

**Issue by yeshasvitirupachuri** [traversaro/traversaro-phd-thesis#15]
It will be very useful if there is a nice way to cite the thesis and update the `readme` of the repo with the citation details. Thanks.

**Comment by traversaro** [comment]
To have a meaningful DOI, I uploadted the thesis on ZENODO at https://zenodo.org/record/3564797#.XelaM9Eo_0q . The bib code (that I will  add in the README) is: 
~~~
@phdthesis{traversaro2017thesis,
  author       = {Traversaro, Silvio},
  title        = {{Modelling, Estimation and Identification of Humanoid Robots Dynamics}},
  school       = {University of Genoa},
  year         = 2017,
  month        = apr,
  doi          = {10.5281/zenodo.3564797},
  url          = {https://doi.org/10.5281/zenodo.3564797}
}
~~~
for exactly the version 1.0.1 (the latest available) or: 
~~~
@phdthesis{traversaro2017thesis,
  author       = {Traversaro, Silvio},
  title        = {{Modelling, Estimation and Identification of Humanoid Robots Dynamics}},
  school       = {University of Genoa},
  year         = 2017,
  month        = apr,
  doi          = {10.5281/zenodo.3564796},
  url          = {https://doi.org/10.5281/zenodo.3564796}
}
~~~
for a generic reference to the phd thesis, without a specific reference to the version, see https://help.zenodo.org/#versioning for more info.

**Comment by yeshasvitirupachuri** [comment]
Thanks @traversaro 
Closing this issue.

**Comment by traversaro** [comment]
Thanks, I will keep the issue open to track the update of the README.

**Comment by traversaro** [comment]
cc @CarlottaSartore
