### ISSUE TITLE
Investigate and fix link pdf 

### ISSUE THREAD

**Issue by DanielePucci** [traversaro/traversaro-phd-thesis#21]
@traversaro  it seems to me that the link to the pdf file of the thesis in the [README](https://github.com/traversaro/traversaro-phd-thesis/blob/master/README.md) is broken:

![image](https://user-images.githubusercontent.com/5045846/105500098-af562000-5cc2-11eb-88ca-189bf60dbbc4.png)

**Comment by traversaro** [comment]
Fixed by https://github.com/traversaro/traversaro-phd-thesis/commit/2326eddf667ec5246c1486a04adc14497d1b0a7b .
