### ISSUE TITLE
errata-còrrige tab 2.2 pag 20  

### ISSUE THREAD

**Issue by GiulioRomualdi** [traversaro/traversaro-phd-thesis#22]
There are some typos in table 2.2 of page 30 

![image](https://user-images.githubusercontent.com/16744101/143299660-50903b3f-7732-40ff-b017-a31014035beb.png)

@traversaro let me know if I should open a PR to fix it

**Comment by traversaro** [comment]
Thanks, feel free to open a PR if you like!
