### ISSUE TITLE
Chapter 2 Equation 2.85 typo

### ISSUE THREAD

**Issue by lrapetti** [traversaro/traversaro-phd-thesis#6]
In the following equation for the Rigid Body total momentum derivate
![Screen Shot 2019-08-30 at 12 01 47](https://user-images.githubusercontent.com/35487806/64012496-1bf4db80-cb1e-11e9-8b35-3687790e0ca7.png)

I think there are the two following typos:
- in the second equation, the wrenches should be expressed as $\_{G[A]}f\^x$ (in $G[A]$ reference).
- in the third equation the rotation matrix $^AR_G^T$ should not be present since it cancels out after multiplying by $\_{G[A]}X^B$.
- in the second equation I think it would be also good to express respect to which frame $g$ is defined, and to specify the rotation matrix $R^T$ where is defined (${R^T}g \to {^AR_G^T}^Ag$)

**Comment by traversaro** [comment]
Fixed in https://github.com/traversaro/phd-thesis/pull/19 .
