### ISSUE TITLE
Chapter 2 Equation 2.78 & 2.75 typo 

### ISSUE THREAD

**Issue by lrapetti** [traversaro/traversaro-phd-thesis#7]
In the Newton-Euler equation for the rigid body in Mixed acceleration, the acceleration is written as _right-trivialized_ ($^A \dot{\mathrm{v}}\_{A,B}$) instead of _mixed_ ($^{B[A]} \dot{\mathrm{v}}\_{A,B}$)

**Comment by prashanthr05** [comment]
Chapter 2 Equation 2.75 has an additional $\mathbb{M}$

**Comment by traversaro** [comment]
Given the new CI system, I also accept pull requests that once accepter will be automatically reflected in the generated PDF at https://github.com/traversaro/phd-thesis/pull/9 .

**Comment by lrapetti** [comment]
> Chapter 2 Equation 2.75 has an additional M

in the same equation it is also missing a sign "-" before the gravity term.

Furthermore, in 2.74 the sign "-" should be a "+" accordingly to 2.73

**Comment by traversaro** [comment]
Fixed in https://github.com/traversaro/phd-thesis/pull/19 by @lrapetti , thanks!
